Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64" 
  config.vm.network "forwarded_port", guest: 3000, host: 5000
 
  config.vm.box_check_update = false

  config.vm.network "public_network"
  
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
    
      vb.memory = "3072"
    end

  config.vm.provision "shell", inline: <<-SHELL
	  apt-get update
    apt-get upgrade

    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb

    sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0
    sudo apt-get install -y dotnet-sdk-8.0
   SHELL
end